### ISSUE TITLE
Visibly Pushdown

### ISSUE THREAD

**Issue by skingo** [plneappl/TreeLanguages#8]

**Comment by plneappl** [comment]
See for example http://dept-info.labri.fr/~fleury/Formation_Doctorale_2006/papers/AM04.pdf

**Comment by plneappl** [comment]
See https://github.com/plneappl/TreeLanguages/commit/450da1c31aa05f0e1367c10f8be15edf652dc776 and https://github.com/plneappl/TreeLanguages/commit/a6aabed870203ec62026123f60eec773ec536245 for implementation of VPA
